apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: appscode-searchlight
  name: appscode-searchlight
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: appscode-searchlight
  template:
    metadata:
      labels:
        run: appscode-searchlight
    spec:
      containers:
      - args:
        - --icinga-secret-name=appscode-icinga
        - --icinga-secret-namespace=kube-system
        image: appscode/searchlight:1.5.5
        imagePullPolicy: Always
        name: appscode-searchlight
