apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: searchlight-operator
  namespace: kube-system
  labels:
    app: searchlight
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: searchlight
    spec:
      containers:
      - name: operator
        image: appscode/searchlight:canary
        args:
        - run
        - --v=3
        - --config-dir=/srv/searchlight
        ports:
        - containerPort: 56790
          name: http
          protocol: TCP     
        volumeMounts:
          - name: data
            mountPath: /srv/searchlight
      - image: postgres:9.6-alpine
        name: ido
        env:
          - name: PGDATA
            value: /var/lib/postgresql/data/pgdata
        ports:
          - containerPort: 5432
            name: ido
            protocol: TCP
        volumeMounts:
          - name: data
            mountPath: /var/lib/postgresql/data
      volumes:
        - name: data
          emptyDir: {}
