apiVersion: v1
kind: Secret
metadata:
  name: searchlight-operator
  namespace: kube-system
  labels:
    app: searchlight
data:
  ICINGA_WEB_UI_PASSWORD: Y2hhbmdlaXQ=
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: searchlight-operator
  namespace: kube-system
  labels:
    app: searchlight
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: searchlight
    spec:
      containers:
      - name: operator
        image: appscode/searchlight:canary
        imagePullPolicy: Always
        args:
        - run
        - --v=3
        - --config-dir=/srv
        - --notifier-secret-name=searchlight-operator
        ports:
        - name: http
          containerPort: 56790
          protocol: TCP
        volumeMounts:
        - name: data
          mountPath: /srv
        - name: tmp
          mountPath: /tmp
      - name: icinga
        image: appscode/icinga:canary
        imagePullPolicy: Always
        ports:
        - name: api
          containerPort: 5665
          protocol: TCP
        - name: web
          containerPort: 60006
          protocol: TCP
        volumeMounts:
        - name: data
          mountPath: /srv
        - name: tmp
          mountPath: /tmp
      - name: ido
        image: appscode/postgres:9.5-alpine
        imagePullPolicy: Always
        env:
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        ports:
        - name: ido
          containerPort: 5432
          protocol: TCP
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
        - name: tmp
          mountPath: /tmp
      volumes:
      - name: data
        emptyDir: {}
      - name: tmp
        emptyDir: {}
---
kind: Service
apiVersion: v1
metadata:
  name: searchlight-operator
  namespace: kube-system
  labels:
    app: searchlight
spec:
  ports:
  - name: web
    port: 80
    targetPort: web
  - name: api
    port: 5665
    targetPort: api
  - name: http
    port: 56790
    targetPort: web
  selector:
    app: searchlight
  type: NodePort
