{{- $ca := genCA "ca" 3650 }}
{{- $cn := include "searchlight.fullname" . -}}
{{- $altName1 := printf "%s.%s" $cn .Release.Namespace }}
{{- $altName2 := printf "%s.%s.svc" $cn .Release.Namespace }}
{{- $cert := genSignedCert $cn nil (list $altName1 $altName2) 3650 $ca }}
apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1alpha1.admission.monitoring.appscode.com
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: "{{ template "searchlight.name" . }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
spec:
  group: admission.monitoring.appscode.com
  version: v1alpha1
  service:
    namespace: {{ .Release.Namespace }}
    name: {{ template "searchlight.fullname" . }}
  caBundle: {{ b64enc $ca.Cert }}
  groupPriorityMinimum: {{ .Values.apiserver.groupPriorityMinimum }}
  versionPriority: {{ .Values.apiserver.versionPriority }}
---
apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1alpha1.incidents.monitoring.appscode.com
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: "{{ template "searchlight.name" . }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
spec:
  group: incidents.monitoring.appscode.com
  version: v1alpha1
  service:
    namespace: {{ .Release.Namespace }}
    name: {{ template "searchlight.fullname" . }}
  caBundle: {{ b64enc $ca.Cert }}
  groupPriorityMinimum: {{ .Values.apiserver.groupPriorityMinimum }}
  versionPriority: {{ .Values.apiserver.versionPriority }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "searchlight.fullname" . }}-apiserver-cert
  namespace: {{ .Release.Namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: "{{ template "searchlight.name" . }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
type: Opaque
data:
  tls.crt: {{ b64enc $cert.Cert }}
  tls.key: {{ b64enc $cert.Key }}
---
{{ if .Values.rbac.create }}
# to read the config for terminating authentication
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "searchlight.fullname" . }}-apiserver-extension-server-authentication-reader
  namespace: kube-system
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: "{{ template "searchlight.name" . }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: extension-apiserver-authentication-reader
subjects:
- kind: ServiceAccount
  name: {{ template "searchlight.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
---
# to delegate authentication and authorization
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "searchlight.fullname" . }}-apiserver-auth-delegator
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: "{{ template "searchlight.name" . }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: {{ template "searchlight.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{ end }}
