appscodeicinga:

## Ihinga configaration
## https://github.com/appscode/searchlight/blob/master/docs/user-guide/icinga2/deployment.md#create-deployment
##

  env: |-
    ICINGA_WEB_HOST=127.0.0.1
    ICINGA_WEB_PORT=5432
    ICINGA_WEB_DB=icingawebdb
    ICINGA_WEB_USER=icingaweb
    ICINGA_WEB_PASSWORD=12345678
    ICINGA_WEB_ADMIN_PASSWORD=admin
    ICINGA_IDO_HOST=127.0.0.1
    ICINGA_IDO_PORT=5432
    ICINGA_IDO_DB=icingaidodb
    ICINGA_IDO_USER=icingaido
    ICINGA_IDO_PASSWORD=12345678
    ICINGA_API_USER=icingaapi
    ICINGA_API_PASSWORD=12345678

## Use <icinga-service-name>.<namespace> in ICINGA_ADDRESS
##

    ICINGA_ADDRESS=my-release-searchlight-appscode-icinga.default
# caCrt:
# icingaKey:
# icingaCrt:
# notifyVia:

## Hipchat notifier
## ref https://github.com/appscode/searchlight/blob/master/docs/user-guide/notifier/hipchat.md#set-environment-variables
##

# hipchatAuthToken:
# hipchatTo:

## Mailgun notifier
## ref: https://github.com/appscode/searchlight/blob/master/docs/user-guide/notifier/mailgun.md#configure
##

# mailgunDomain:
# mailgunAPIKey:
# mailgunPublicAPIKey:
# mailgunFrom:
# mailgunTo:

## SMTP notifier
## ref: https://github.com/appscode/searchlight/blob/master/docs/user-guide/notifier/smtp.md#configure
##

# smtpHost:
# smtpPort:
# smtpInsecureSkipVerify:
# smtpUsername:
# smtpPassword:
# smtpFrom:
# smtpTo:

## Twilio notifier
## ref: https://github.com/appscode/searchlight/blob/master/docs/user-guide/notifier/twilio.md
##

# twilioAccountSid:
# twilioAuthToken:
# twilioFrom:
# twilioTo:

## Slack notifier.
## ref: https://github.com/appscode/searchlight/blob/master/docs/user-guide/notifier/slack.md
##

# slackAuthToken:
# slackChannel:

## Plivo notifier
## ref: https://github.com/appscode/searchlight/blob/master/docs/user-guide/notifier/plivo.md
##

# plivoAuthId:
# plivoAuthToken:
# plivoFrom:
# plivoTo:

## Icinga container configaration
##

  icinga:
    image: appscode/icinga
    imageTag: 1.5.4-k8s
    apiPort: 5665
    tcpPort: 80

## Postgress configaration
##

  ido:
    image: appscode/postgres
    imageTag: 9.5-v3-db
    idoPort: 5432

## Icinga secret type
##

  type: Opaque
## Service target port
##

  apiTargetPort: 5665
  webTargetPort: 60006

## Search light configaration
##

appscodesearchlight:

## Searchlight image
##
  image: appscode/searchlight

## Searchlight image pull policy
##

  imagePullPolicy: Always

## Searchlight image tag
##

  imageTag: 1.5.4
