apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: appscode-icinga
  namespace: kube-system
  labels:
    run: appscode-icinga
spec:
  replicas: 1
  selector:
    matchLabels:
      run: appscode-icinga
  template:
    metadata:
      labels:
        run: appscode-icinga
    spec:
      containers:
      - image: appscode/icinga:1.5.4-k8s
        name: icinga
        ports:
        - containerPort: 5665
          name: api
          protocol: TCP
        - containerPort: 60006
          name: tcp
          protocol: TCP
        volumeMounts:
          - name: data-volume
            mountPath: /var/pv
          - name: script-volume
            mountPath: /var/db-script
          - name: appscode-icinga
            mountPath: /srv/icinga2/secrets
      - image: appscode/postgres:9.5-v3-db
        name: ido
        args:
          - basic
          - './setup-db.sh'
        ports:
          - containerPort: 5432
            name: ido
            protocol: TCP
        volumeMounts:
          - name: data-volume
            mountPath: /var/pv
          - name: script-volume
            mountPath: /var/db-script
      volumes:
        - name: data-volume
          emptyDir: {}
        - name: script-volume
          emptyDir: {}
        - name: appscode-icinga
          secret:
            secretName: appscode-icinga
