kind: Service
apiVersion: v1
metadata:
  name: appscode-icinga
  namespace: kube-system
  labels:
    run: appscode-icinga
spec:
  ports:
    - name: web
      port: 80
      targetPort: web
    - name: api
      port: 5665
      targetPort: api
  selector:
    run: appscode-icinga
