apiVersion: v1
kind: Secret
metadata:
  labels:
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    heritage: "{{.Release.Service}}"
    release: "{{.Release.Name}}"
  name: {{ template "fullname" . }}-appscode-icinga
type: {{.Values.appscodeicinga.type}}
data:
  .env: {{default "" .Values.appscodeicinga.env | b64enc | quote}}
  ca.cert: {{default "" .Values.appscodeicinga.caCrt | b64enc | quote}}
  icinga.key: {{default "" .Values.appscodeicinga.ichingaKey| b64enc | quote}}
  icinga.crt: {{default "" .Values.appscodeicinga.ichingaCrt| b64enc | quote}}
  notify_via: {{default "" .Values.appscodeicinga.notifyVia| b64enc | quote}}
  hipchat_auth_token: {{default "" .Values.appscodeicinga.hipchatAuthToken| b64enc | quote}}
  hipchat_to: {{default "" .Values.appscodeicinga.hipchatTo| b64enc | quote}}
  mailgun_domain: {{default "" .Values.appscodeicinga.mailgunDomain| b64enc | quote}}
  mailgun_api_key: {{default "" .Values.appscodeicinga.mailgunAPIKey| b64enc | quote}}
  mailgun_public_api_key: {{default "" .Values.appscodeicinga.mailgunPublicAPIKey| b64enc | quote}}
  mailgun_from: {{default "" .Values.appscodeicinga.mailgunFrom| b64enc | quote}}
  mailgun_to: {{default "" .Values.appscodeicinga.mailgunTo| b64enc | quote}}
  smtp_host: {{default "" .Values.appscodeicinga.smtpHost| b64enc | quote}}
  smtp_port: {{default "" .Values.appscodeicinga.smtpPort| b64enc | quote}}
  smtp_insecure_skip_verify: {{default "" .Values.appscodeicinga.smtpInsecureSkipVerify| b64enc | quote}}
  smtp_username: {{default "" .Values.appscodeicinga.smtpUsername| b64enc | quote}}
  smtp_password: {{default "" .Values.appscodeicinga.smtpPassword| b64enc | quote}}
  smtp_from: {{default "" .Values.appscodeicinga.smtpFrom| b64enc | quote}}
  smtp_to: {{default "" .Values.appscodeicinga.smtpTo| b64enc | quote}}
  twilio_account_sid: {{default "" .Values.appscodeicinga.twilioAccountSid| b64enc | quote}}
  twilio_auth_token: {{default "" .Values.appscodeicinga.twilioAuthToken| b64enc | quote}}
  twilio_from: {{default "" .Values.appscodeicinga.twilioFrom| b64enc | quote}}
  twilio_to: {{default "" .Values.appscodeicinga.twilioTo| b64enc | quote}}
  slack_auth_token: {{default "" .Values.appscodeicinga.slackAuthToken| b64enc | quote}}
  slack_channel:  {{default "" .Values.appscodeicinga.slackChannel| b64enc | quote}}
  plivo_auth_id: {{default "" .Values.appscodeicinga.plivoAuthId| b64enc | quote}}
  plivo_auth_token: {{default "" .Values.appscodeicinga.plivoAuthToken| b64enc | quote}}
  plivo_from: {{default "" .Values.appscodeicinga.plivoFrom| b64enc | quote}}
  plivo_to: {{default "" .Values.appscodeicinga.plivoTo| b64enc | quote}}