apiVersion: v1
kind: Service
metadata:
  labels:
    chart: {{.Chart.Name}}-{{.Chart.Version}}
    heritage: {{.Release.Service}}
    release: {{.Release.Name}}
    run: {{ template "fullname" . }}-appscode-icinga
  name: {{ template "fullname" . }}-appscode-icinga
spec:
  ports:
  - name: web
    port: {{.Values.appscodeicinga.webTargetPort}}
    targetPort: tcp
  - name: api
    port: {{.Values.appscodeicinga.apiTargetPort}}
    targetPort: api
  selector:
    run: "{{ template "fullname" . }}-appscode-icinga"
